// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28ZMqw5KXb2q_WGry4uXuovv6n3NrcKg',
    appId: '1:22993218649:android:bd2e6b3771acdead1f9548',
    messagingSenderId: '22993218649',
    projectId: 'nemochatapp-7fc38',
    storageBucket: 'nemochatapp-7fc38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7psF7fafxZ6f9wUgejurkQlJdWyqg858',
    appId: '1:22993218649:ios:32dcad539db401961f9548',
    messagingSenderId: '22993218649',
    projectId: 'nemochatapp-7fc38',
    storageBucket: 'nemochatapp-7fc38.appspot.com',
    androidClientId: '22993218649-lo9kdcumirjaalt34han38vf3vgnvql0.apps.googleusercontent.com',
    iosClientId: '22993218649-p1o1ef7vrih7s9r6od5h3rlrfdokt1lg.apps.googleusercontent.com',
    iosBundleId: 'com.nemochatapp.tech',
  );
}
